# Generated by Django 4.0.3 on 2022-04-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review_author_alter_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=0, upload_to='covers/'),
            preserve_default=False,
        ),
    ]
